### ISSUE TITLE
クリエイトコモンズ配下の 2020 Tokyo Metropolitan Governmentクレジットについて

### ISSUE THREAD

**Issue by takashiny** [Code-for-OKINAWA/covid19#101]
## 起こっている問題 / The Problem
- クリエイトコモンズ配下のクレジット

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/661736/78414511-4fb95600-7657-11ea-903d-10a0afe3314a.png)

## 期待する見せ方・挙動 / Expected Behavior
- 東京都のクレジットではなく、沖縄県もしくは開発チームのクレジットでよいのかとおもいました。

## 起こっている問題の再現手段 / Steps to Reproduce
常に参照可能です。

## 動作環境・ブラウザ / Environment
どの動作環境でも参照可能です。

**Comment by amouro** [comment]
If you like can we update the text temporarily to 

**Code for Okinawa** with link to http://code4okinawa.org/ before we have the credit page.

**Comment by masakifujie** [comment]
Thank you!
 I'll do that
