### ISSUE TITLE
OGP画像およびロゴについて

### ISSUE THREAD

**Issue by modanrls** [Code-for-OKINAWA/covid19#105]
## 改善詳細 / Details of Improvement
- ogp画像が上下がきれたトリミングで表示されるので東京都のものをベースに修正
- サイトのロゴが文字詰めなどが整理されていないのを整理

## スクリーンショット / Screenshot
<img width="520" alt="スクリーンショット 2020-04-04 13 43 02" src="https://user-images.githubusercontent.com/8667094/78418784-9b312b80-767a-11ea-905e-1e98b98a4def.png">

![スクリーンショット-2020-04-04-13 44 43](https://user-images.githubusercontent.com/8667094/78418812-d6cbf580-767a-11ea-8ab6-043af52c4004.png)

## 期待する見せ方・挙動 / Expected behavior
- 東京都のogpをベースに修正
![ogp](https://user-images.githubusercontent.com/8667094/78419151-c6694a00-767d-11ea-83ae-df83d7b018c2.png)

-ロゴを東京都のものをベースに修正
![logo](https://user-images.githubusercontent.com/8667094/78418853-185ca080-767b-11ea-901f-fc958cb04d71.jpg)

-修正したファイルをおいておきます。
[https://www.dropbox.com/sh/dnksabjmlu1z6a0/AAAuqnYlbOtsCl0G0DINT5YBa?dl=0](https://www.dropbox.com/sh/dnksabjmlu1z6a0/AAAuqnYlbOtsCl0G0DINT5YBa?dl=0)

**Comment by masakifujie** [comment]
アヤネさん

**Comment by amouro** [comment]
It is recommended to have OPG image in this dimension `1200x630`

**Comment by amouro** [comment]
Codeアプデトしまし
英語版と繁體中文版も作ってもいいですが？

### 翻訳文字：

* 英語版
  * Task force website
* 繁體中文版
  * 新型冠狀病毒
  * 疫情中心

### 東京都OGP画像参考

* 英語版
  * https://stopcovid19.metro.tokyo.lg.jp/ogp/en/ogp-image.png
* 繁體中文版
  * https://stopcovid19.metro.tokyo.lg.jp/ogp/zh-tw/ogp-image.png

**Comment by masakifujie** [comment]
@amouro お願いいたいます

**Comment by amouro** [comment]
#### 英語版
![ogp-okinawa](https://user-images.githubusercontent.com/3444618/78780251-43c3f000-79d9-11ea-8dda-a5fdbccf04f7.png)

#### 繁體中文版
![ogp-okinawa](https://user-images.githubusercontent.com/3444618/78780272-49b9d100-79d9-11ea-9079-cab9f842fba1.png)

**Comment by amouro** [comment]
修正しました、レビューお願いします。

**Comment by modanrls** [comment]
@amouro OGP画像以外に、以下のサイトロゴ

[https://okinawa.stopcovid19.jp/logo.svg](url)
[https://okinawa.stopcovid19.jp/sp_logo.svg](url)

も制作していて、ファイルを格納しておりまして、
かつ編集可能なaiもおいております。
[https://www.dropbox.com/sh/dnksabjmlu1z6a0/AAAuqnYlbOtsCl0G0DINT5YBa?dl=0](url)

優先度の低い内容ではございますが、確認していただけると幸いです。

**Comment by masakifujie** [comment]
公式を外して欲しいです！

**Comment by amouro** [comment]
[ogp.psd.zip](https://github.com/Code-for-OKINAWA/covid19/files/4455454/ogp.psd.zip)
My updated psd file

**Comment by amouro** [comment]
@modanrls 修正するのを手伝ってもいいですか

**Comment by modanrls** [comment]
@amouro @masakifujie 承知しました！

**Comment by modanrls** [comment]
@amouro 
英語についてですが、
"Task Force Website" or "Information Website"
ではどちらが正しいですか？

現状のサイトの英訳は"Information Website"となっています。

<img width="246" alt="スクリーンショット 2020-04-09 23 10 26" src="https://user-images.githubusercontent.com/8667094/78904483-92e05280-7ab7-11ea-9f86-53b59160e60d.png">

**Comment by modanrls** [comment]
日本語は修正しております
https://www.dropbox.com/sh/dnksabjmlu1z6a0/AAAuqnYlbOtsCl0G0DINT5YBa?dl=0

![ogp](https://user-images.githubusercontent.com/8667094/78947209-be872b00-7aff-11ea-9b2f-f102df77be8f.png)

**Comment by modanrls** [comment]
@amouro 

修正しております。

**日本語**
![ogp](https://user-images.githubusercontent.com/8667094/78952566-f77bcb80-7b10-11ea-8e74-58e7d14bbc6c.png)

**英語**
![ogp_en](https://user-images.githubusercontent.com/8667094/78952577-02366080-7b11-11ea-9f85-225b6bd60f07.png)

**繁體中文**
![ogp_zh-tw](https://user-images.githubusercontent.com/8667094/78952592-10847c80-7b11-11ea-9166-93f15c31d705.png)

レビューお願いします。
ファイルは以下にもまとめております。
https://www.dropbox.com/sh/dnksabjmlu1z6a0/AAAuqnYlbOtsCl0G0DINT5YBa?dl=0

**Comment by masakifujie** [comment]
ありがとうございます！
そのままInformation Websiteで！プルリク出してもらってもいいですか？

**Comment by amouro** [comment]
> 英語についてですが、
> "Task Force Website" or "Information Website"
> ではどちらが正しいですか？

@masakifujie Would you like to change? 管理者に聞いてお願いします。

**Comment by amouro** [comment]
プルリクしました。
I'm fine with "Information Website" it was translation from Tokyo English site.

**Comment by masakifujie** [comment]
修正してくれていたのでクローズします！
