### ISSUE TITLE
Map generator failed

### ISSUE THREAD

**Issue by amouro** [Code-for-OKINAWA/covid19#1109]
## 起こっている問題 / The Problem
- Map generator failed in GitHub action

https://github.com/Code-for-OKINAWA/covid19/actions/runs/389700584

## 期待する見せ方・挙動 / Expected Behavior
- Resolve the github action issue

## 動作環境・ブラウザ / Environment
- GitHub Action

**Comment by t-ube** [comment]
当該のマップはすでに使用していないためクローズ
