### ISSUE TITLE
企業の皆様・はたらく皆様へを復活

### ISSUE THREAD

**Issue by masakifujie** [Code-for-OKINAWA/covid19#116]

**Comment by masakifujie** [comment]
まとまっている情報がありました！
https://www.pref.okinawa.jp/site/shoko/rosei/kannsennshou_soudannshiennsaku.html

**Comment by amouro** [comment]
The code is all good. @masakifujie please help review or ask someone to review the link and text.

**Comment by wtnbwtnb** [comment]
@masakifujie  SideNavigation.vueのコメントアウト外してなかったです。close後にすみません
