### ISSUE TITLE
お問い合わせ先一覧復活

### ISSUE THREAD

**Issue by masakifujie** [Code-for-OKINAWA/covid19#117]

**Comment by masakifujie** [comment]
東京のお問い合わせ先一覧です。
https://stopcovid19.metro.tokyo.lg.jp/contacts

**Comment by masakifujie** [comment]
東京が挙げている項目を参考に連絡口まとめてみます！

**Comment by masakifujie** [comment]
サイト全般に関すること・サイトの技術面に関すること
オープンデータ、オープンソースに関すること　→　CODE for OKINAWA  codeforokinawa@gmail.com 

新型コロナウイルス感染症対策本部会議に関すること
都庁来庁者データに関すること　→　必要？県庁？

県公式ホームページに関すること
県公式SNSアカウントに関すること　→　沖縄県庁　098-866-2333

新型コロナウイルス感染症の予防・検査・医療に関すること→　沖縄県　新型コロナウィルス感染症　相談窓口　ＴＥＬ：　０９８－８６６－２１２９　
https://www.pref.okinawa.jp/site/hoken/chiikihoken/kekkaku/2019-ncov.html

県立学校に関すること→　沖縄県教育庁県立学校教育課　098-866-2715
https://www.pref.okinawa.jp/edu/kenritsu/new_corona.html

**Comment by mami-miyagi** [comment]
＠masakifujie
------------------------------
新型コロナウイルス感染症対策本部会議に関すること
都庁来庁者データに関すること　→　必要？県庁？
------------------------------
こちらは載せないでおきますか？

**Comment by mami-miyagi** [comment]
こちらのissue、私が担当します。
