### ISSUE TITLE
陽性患者数の表示を見やすくしたい

### ISSUE THREAD

**Issue by azurata09** [Code-for-OKINAWA/covid19#1170]
## 改善詳細 / Details of Improvement
- 陽性患者数のグラフが昨年1月から最近までを常に表示しているため、近況を読み取りづらい

![2021-02-08 05 38 51 okinawa stopcovid19 jp c15d193d7d21](https://user-images.githubusercontent.com/31302074/107158903-4106a280-69d0-11eb-9a0f-a3c43fa4660f.png)

## 期待する見せ方・挙動 / Expected behavior
- 東京版のように、一定期間を表示するようにし、スライダーで過去の数字を閲覧できるようにする

![2021-02-08 05 39 06 stopcovid19 metro tokyo lg jp 137c4635443c](https://user-images.githubusercontent.com/31302074/107158922-511e8200-69d0-11eb-9ea1-0f9175de2768.png)

**Comment by azurata45** [comment]
東京版のPull Requestを参考に実装してみたのですが、Forkして時間も経っていることもあり、コンポーネントの構造がかなり違うためあまり参考になりませんでした。そのため、独自で実装する実装がありそうです。
