### ISSUE TITLE
埋め込み用コードのスタイル修正

### ISSUE THREAD

**Issue by kaitoohsiro** [Code-for-OKINAWA/covid19#1183]
## 改善詳細 / Details of Improvement
- snsのアイコンスタイルが崩れている

## スクリーンショット / Screenshot

![スクリーンショット 2021-02-24 14 30 56](https://user-images.githubusercontent.com/53632978/108952792-7f2ce300-76ad-11eb-8067-a9f849016f84.png)
<img width="287" alt="スクリーンショット 2021-02-25 15 39 03" src="https://user-images.githubusercontent.com/53632978/109113815-2d08c200-7780-11eb-9a84-fe3aa3bebc66.png">

## 期待する見せ方・挙動 / Expected behavior
- [東京都版](https://stopcovid19.metro.tokyo.lg.jp/)のように崩れているところを直したい
![スクリーンショット 2021-02-24 14 31 14](https://user-images.githubusercontent.com/53632978/108952781-7b995c00-76ad-11eb-8b0b-afe2e2843afc.png)
<img width="287" alt="スクリーンショット 2021-02-25 15 38 29" src="https://user-images.githubusercontent.com/53632978/109113839-32660c80-7780-11eb-8190-763614ced3a5.png">
## 動作環境・ブラウザ / Environment
- macOS /
- Chrome / Safari / Firefox /

**Comment by kaitoohsiro** [comment]
自分で見つけたことですが、、、
やります

**Comment by amouro** [comment]
@kaitoohsiro ありがとうございます。マージしました
