### ISSUE TITLE
開発中の画面に存在する公開サイトへのリンクで東京版のサイトに飛んでしまう

### ISSUE THREAD

**Issue by azurata45** [Code-for-OKINAWA/covid19#122]
## 起こっている問題 / The Problem
- 開発中の画面に表示される公開サイトへのリンク踏むと、東京版のサイトに飛んでしまう

## スクリーンショット / Screenshot
![development-mode-screenshot](https://user-images.githubusercontent.com/31302074/78455017-da8d6580-76d6-11ea-996a-050bafa0f06b.png)

## 期待する見せ方・挙動 / Expected Behavior
- 該当リンクのURLを沖縄版公開サイトのURLに変更

**Comment by chinen-octtn** [comment]
確認します！

**Comment by chinen-octtn** [comment]
こちらのプルリクはマージしました！ありがとうございます！
closeします！
