### ISSUE TITLE
「県警戒レベル判断指標」のカード追加

### ISSUE THREAD

**Issue by m3n3m** [Code-for-OKINAWA/covid19#1293]
## 改善詳細 / Details of Improvement
- 「感染者発生状況」の画像の代わりに「県警戒レベル判断指標」を表示する
- https://okinawa-covid19map.netlify.app/

## スクリーンショット / Screenshot
<img width="467" alt="スクリーンショット 2021-06-08 16 51 56" src="https://user-images.githubusercontent.com/39450931/121145407-e3993a00-c879-11eb-955a-4f5d2232f16c.png">

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by t-ube** [comment]
完了済み
