### ISSUE TITLE
aboutページにおけるGitHubへのリンク先が間違っている。

### ISSUE THREAD

**Issue by anosillus** [Code-for-OKINAWA/covid19#135]
## 起こっている問題 / The Problem
- aboutページにおけるGitHubへリンクURLが東京都版のGitHubレポジトリへのURLになっているので、混乱を避けるために沖縄版の当レポジトリに変更する必要がある。

## 期待する見せ方・挙動 / Expected Behavior
- about.vue上のファイルにおいて、{githubRepo}の値を以下のように修正する
修正前： https://github.com/tokyo-metropolitan-gov/covid19
修正後： https://github.com/Code-for-OKINAWA/covid19

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ryu1-1uyr** [comment]
![image](https://user-images.githubusercontent.com/29749298/78493388-1af6ed00-7784-11ea-9a46-0833ad2fce8a.png)
こちらの方のリンクで確認

**Comment by mami-miyagi** [comment]
ありがとうございます。変更します。
