### ISSUE TITLE
英語版・繁体字版の微修正

### ISSUE THREAD

**Issue by mami-miyagi** [Code-for-OKINAWA/covid19#150]
## 改善詳細 / Details of Improvement
- 英語版と繁体字版の微修正をお願いします。

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by amouro** [comment]
![Image from iOS](https://user-images.githubusercontent.com/3444618/78531954-5f849600-7821-11ea-8d35-568c5fbb4649.jpg)
// by Ayane Ish

**Comment by amouro** [comment]
### About this site
- still has the Tokyo version on the top text box): please change to below,

This website was opened by volunteers of Code for Okinawa in association with the Okinawa Prefectural Government to provide the latest information on the novel coronavirus disease (COVID-19).
By conveying official information of the Okinawa Prefectural Government and objective data in an easy-to-understand way, this site aims to allow Okinawa residents, companies with offices in Okinawa, and visitors to Okinawa to grasp the current situation and take measures and precautions accordingly.
It uses an open source licence that permits copying and redistribution, and is based on the Tokyo Metropolitan Government COVID-19 Task Force website.

// by Ayane Ish

**Comment by amouro** [comment]
修正した
