### ISSUE TITLE
翻訳しに Transifex 連携する / Integrate Transifex for translation

### ISSUE THREAD

**Issue by amouro** [Code-for-OKINAWA/covid19#154]
## 改善詳細 / Details of Improvement
Follow the Tokyo Covid-19 website to integrate [Transifex](https://www.transifex.com/) for translation.

The integration requires integration setting in the repo

## スクリーンショット / Screenshot
Commit history on tokyo-metropolitan-gov/covid19
![image](https://user-images.githubusercontent.com/3444618/78574609-2e2db980-7865-11ea-810b-9bb021cf8bc9.png)

## 期待する見せ方・挙動 / Expected behavior
- Ask translation contributor to use Transifex for translation other than ja
- Integrate and allow bot of Transifex to update the locale file

**Comment by masakifujie** [comment]
お疲れ様です！
こちらはどのように動いていますか？
ラベルは確認中とさせていただきます。

**Comment by amouro** [comment]
@masakifujie 
This requires a Transifex project and the repo owner to setup Transifex integration
detail instruction can be found here https://docs.transifex.com/transifex-github-integrations/github-tx-ui

**Comment by amouro** [comment]
@masakifujie I'm trying the integration on my forked repo.
If success, I can map it to this repository.
![image](https://user-images.githubusercontent.com/3444618/78857649-e83f4400-7a64-11ea-8bb7-2f010d5a799c.png)

**Comment by amouro** [comment]
![image](https://user-images.githubusercontent.com/3444618/78859094-5259e800-7a69-11ea-8c26-2ed2592307f2.png)

**Comment by masakifujie** [comment]
It' s cool!
If you possible ,Could you try it?
then please pull request!

**Comment by amouro** [comment]
@masakifujie I've sent a Transifex integration request to CfO account. If you can approve it please help.
I'll make a PR soon to make the repo ready to use Transifex

**Comment by amouro** [comment]
PR created #203 

Please let me know if integration is configured.
![image](https://user-images.githubusercontent.com/3444618/78880821-e8edcf80-7a90-11ea-8b0a-cb0c70341e67.png)

**Comment by masakifujie** [comment]
Okay!
You can configure it!

**Comment by masakifujie** [comment]
Thank you!

**Comment by amouro** [comment]
I still see it's requesting, and can't read the repo from their.

**Comment by amouro** [comment]
Reopen for confirmation until the integration works

**Comment by amouro** [comment]
@wanwanland or @mami-miyagi can you help accept the request of install Transifex? If you're the owner of Code for Okinawa organization on Github

**Comment by amouro** [comment]
FYI the installation Path https://github.com/apps/transifex-integration/installations/new

**Comment by mami-miyagi** [comment]
＠amouro
Should I choose "All repositories" or "Only select repositories (select repositries)"?

<img width="548" alt="スクリーンショット 2020-04-09 21 14 59" src="https://user-images.githubusercontent.com/38314424/78894002-412fcc00-7aa7-11ea-990c-97afa4e3e5e7.png">

**Comment by masakifujie** [comment]
Chrisさんの返事待ちます！

**Comment by amouro** [comment]
It's ok to select only covid19 repository
// @mami-miyagi

**Comment by masakifujie** [comment]
Is this issue done?

**Comment by amouro** [comment]
@masakifujie 
Now I see the integration is set. But the issue is not done yet.
I will need to setup Transifex and link it to the repo.

**Comment by amouro** [comment]
The integration is finished. please start using the Transifex to provide translation to English, 繁體中文 and やさしい日本語

I also update the guideline in TRANSLATION document for CfO version.
Please take a loot here 
https://github.com/Code-for-OKINAWA/covid19/blob/6baf9d6eaa22d621e602068e872ab9430b928ba1/TRANSLATION.md

**Comment by amouro** [comment]
Transifex 連携しました。今から、英語、中文とやさしい日本語の翻訳追加するのが、Transifexでしてください。
