### ISSUE TITLE
グラフ内の英語が強制改行されている

### ISSUE THREAD

**Issue by minami-backham** [Code-for-OKINAWA/covid19#161]
## 起こっている問題 / The Problem
- 言語で英語を選択している場合、グラフ内の文字が単語の途中でも強制改行されるため、読みづらい。

## スクリーンショット / Screenshot
![Latest updates on COVID-19 in Okinawa   沖縄県 新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/57670024/78637967-6c1ef200-78e6-11ea-882d-57d2f982d1f3.png)

## 期待する見せ方・挙動 / Expected Behavior
- 強制改行やめる。

現在
```
word-break: break-all;
```

こうしたら良さそう
```
word-break: normal;
word-wrap: break-word;
overflow-wrap: break-word;
```

## 起こっている問題の再現手段 / Steps to Reproduce
1. 言語の選択を英語にする

**Comment by amouro** [comment]
やります
関連issue https://github.com/tokyo-metropolitan-gov/covid19/pull/1782

**Comment by amouro** [comment]
修正しました
