### ISSUE TITLE
エリア別感染状況の画像を表示する

### ISSUE THREAD

**Issue by wanwanland** [Code-for-OKINAWA/covid19#176]

**Comment by masakifujie** [comment]
表示できるようになったら、今度は更新方法を確認させてください！

**Comment by masakifujie** [comment]
表示場所まだ決まってないですよね？

**Comment by wanwanland** [comment]
![image](https://user-images.githubusercontent.com/1308577/78798938-821ad880-79f4-11ea-979b-333476b73cbf.png)

**Comment by wanwanland** [comment]
説明資料
https://github.com/Code-for-OKINAWA/covid19/wiki/%E6%B2%96%E7%B8%84%E7%9C%8C%E5%86%85%E6%84%9F%E6%9F%93%E8%80%85%E7%99%BA%E7%94%9F%E7%8A%B6%E6%B3%81%E6%9B%B4%E6%96%B0%E6%96%B9%E6%B3%95
