### ISSUE TITLE
【陽性患者の属性】表記を見やすくしたい

### ISSUE THREAD

**Issue by chinen-octtn** [Code-for-OKINAWA/covid19#303]
## 改善詳細 / Details of Improvement
- 見出しを「退院」→「入退院状況」に変更
- 表の下の注釈に追加「※入院調整中には、確認中も含む」

## スクリーンショット / Screenshot
![issue](https://user-images.githubusercontent.com/32406502/79294231-9be67f00-7f10-11ea-83ad-1afbbdc6db55.png)

**Comment by amouro** [comment]
やさしい日本語お願いします
```
"※退院には、死亡退院を含む": ""
```

**Comment by m3n3m** [comment]
```
"※退院には、死亡退院を含む": "※死亡(しぼう)もはいります"
```

**Comment by m3n3m** [comment]
```
"※入院調整中には、確認中も含む": "※「入院（にゅういん）の 調整（ちょうせい）をしています」には、まだ 確認中（かくにんちゅう）の ひとも はいります"
```

**Comment by masakifujie** [comment]
後は通常盤の表示も必要もですね！どちらのファイルから変更しましたか？
