### ISSUE TITLE
英語i18nの読みやすさを改善

### ISSUE THREAD

**Issue by xdkang** [Code-for-OKINAWA/covid19#310]
## 改善詳細 / Details of Improvement
- 英語文の曖昧さを減らし情報をもっと正確に伝えますように
- 文法の誤りを訂正

## 動作環境・ブラウザ / Environment
- all

**Comment by amouro** [comment]
Thanks @xdkang. I reviewed the change mainly for the current site.
I'd like to discuss on one translation with you, please see the review note at #311
