### ISSUE TITLE
感染者発生状況詳細マップに但し書き追加

### ISSUE THREAD

**Issue by m3n3m** [Code-for-OKINAWA/covid19#326]
## 改善詳細 / Details of Improvement
「プロットしたところに市町村の代表点以上の意味はない」ことを表す但し書きが必要。
スクリーンショットのように地図はかなり拡大して見ることができるため、この地点で感染がまとまって発生したようにも見えてしまう。注意が必要。

## スクリーンショット / Screenshot
<img width="578" alt="スクリーンショット 2020-04-16 20 30 45" src="https://user-images.githubusercontent.com/39450931/79451341-5d8cb500-8021-11ea-9ee4-8a0398e32687.png">

## 期待する見せ方・挙動 / Expected behavior
- 「地図上には、感染者の発生した「市区町村」、「保健所管轄区域」をプロットしています。プロット先の地点は、各市町村の本庁舎所在地、保健所の所在地とします。」などを地図の下に但し書きを記載。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by masakifujie** [comment]
よろしくお願いします！

**Comment by amouro** [comment]
![image](https://user-images.githubusercontent.com/3444618/79564641-04d51f00-80ea-11ea-9b47-c0c57e560169.png)
Missing translatable string

**Comment by amouro** [comment]
地図上には、感染者の発生した「市区町村」、「保健所管轄区域」をプロットしています。プロット先の地点は、各市町村の本庁舎所在地、保健所の所在地とします。

### English (en)
The occurrence of the infected patients on the map is plotted. The plot points will be the location of each municipal government building and public health center.

### 繁體中文 (zh-tw)
地圖上顯示的感染者所在「市區町村」、「保健所管轄區域」並非真實位置。地點將標示於各市町村的主要辦公廳舍，或保健所所在地。
