### ISSUE TITLE
ogp_builder が staging リリース時にも走っていて失敗している

### ISSUE THREAD

**Issue by amouro** [Code-for-OKINAWA/covid19#387]
This is from Tokyo branch, we have the same issues here.
### Resolution
https://github.com/tokyo-metropolitan-gov/covid19/pull/3357

## 起こっている問題 / The Problem
- ogp_builder が staging リリース時にも走っていて失敗している

## 期待する見せ方・挙動 / Expected Behavior
- OGP生成は、masterブランチへのリリース時のみで問題ないので、staging リリース時の起動を停止する

## 起こっている問題の再現手段 / Steps to Reproduce
- 例えばこれ。
  https://github.com/tokyo-metropolitan-gov/covid19/actions/runs/79326949 protected branchへのpushが原因

**Comment by wanwanland** [comment]
@amouro 
この問題stagingだけではなく、productionでも起きています。
調査と対応急がないのであれば僕が対応します。
https://github.com/Code-for-OKINAWA/covid19/actions/runs/82464380

**Comment by amouro** [comment]
@wanwanland 
そうです、それは実際には production の問題と思います。 このコミットにより staging が削除され、問題が解決しました。
https://github.com/tokyo-metropolitan-gov/covid19/pull/3357/files
![image](https://user-images.githubusercontent.com/3444618/79716259-26641f80-8311-11ea-83d0-129adac8cfd6.png)

**Comment by amouro** [comment]
@masakifujie I don't see this issue has been fixed in code.
