### ISSUE TITLE
新しい検査陽性者の状況画像のデザイン

### ISSUE THREAD

**Issue by amouro** [Code-for-OKINAWA/covid19#392]
## 改善詳細 / Details of Improvement
- Okinawa Prefecture Gov will not disclose the patients status anymore.
- We have to rebuild the 検査陽性者の状況 graph

## スクリーンショット / Screenshot

![Screen Shot on 2020-04-20 at 21:13:42](https://user-images.githubusercontent.com/3444618/79750402-dce4f600-834b-11ea-8aae-7d4d8c5ff98d.png)

## 期待する見せ方・挙動 / Expected behavior
- 新しい検査陽性者の状況画像のデザイン

## NEW CSV Data Sample
![image](https://user-images.githubusercontent.com/3444618/79750344-c2ab1800-834b-11ea-87e2-074aae98f6ff.png)

**Comment by wanwanland** [comment]
【結論】
一旦このままでお願いします。

【理由】
１・重症・軽症は重要なデータだと思います。
２・Ayane Ish に電話して相談しました。
３・ISCOに情報もらえないか交渉してもらえます。

**Comment by amouro** [comment]
同意すると思います

I suggest to make the change as the following plan

* Mapping `470007_okinawa_covid19_patient.symptom.csv` data for `死亡` and `退院`
* Mapping `summary.csv` for 重症 and 軽症 
   * 軽症 = 陽性者数 - 重症
* Count 陽性者数 from `470007_okinawa_covid19_patients.csv`

**Comment by wanwanland** [comment]
重症 and 軽症はデータとしてもらえないので、`470007_okinawa_covid19_patient.symptom.csv`荷手書きで入れたほうがいいと思います。

**Comment by wanwanland** [comment]
重症, 軽症, 死亡はデータとしてもらえないので、470007_okinawa_covid19_patient.symptom.csvに手書きで入れたほうがいいと思います。

we can`t get 重症, 軽症, 死亡 date so I think that   we  write 470007_okinawa_covid19_patient.symptom.csv

**Comment by amouro** [comment]
summary.csv is better for us to work. We still need to rely on `470007_okinawa_covid19_patient.symptom.csv` to get number of Death, Discharged, different hospitalized.

**Comment by amouro** [comment]
![image](https://user-images.githubusercontent.com/3444618/79979879-329cd800-84dd-11ea-84d5-04038a4496ad.png)

Based on the `470007_okinawa_covid19_patient.symptom.csv` and our own number of `重症 `
I update the converter.

**Comment by amouro** [comment]
![image](https://user-images.githubusercontent.com/3444618/79981079-0a15dd80-84df-11ea-883c-e5ba2ddfd1aa.png)

Please keep record for every day now

**Comment by masakifujie** [comment]
https://codeforokinawa.slack.com/archives/C01119TC1HQ/p1587703130491200?thread_ts=1587702958.491100&cid=C01119TC1HQ
ISCOから情報がもらえたら重傷者など表示可能
