### ISSUE TITLE
企業の皆様・働く皆様へ　「雇用調整助成金」に対するweb相談窓口を追加

### ISSUE THREAD

**Issue by masakifujie** [Code-for-OKINAWA/covid19#440]
![県内の最新感染動向___沖縄県_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/62975418/80270391-7583c900-86f2-11ea-9903-5ef811883476.jpg)

**Comment by masakifujie** [comment]
https://www.okinawa-bank.co.jp/news_release/2020042400017/

**Comment by amouro** [comment]
I think the information is outdated, do you want to add another one?

**Comment by t-ube** [comment]
すでに追加済みのためクローズする
