### ISSUE TITLE
flowのページの相談目安を更新する

### ISSUE THREAD

**Issue by m3n3m** [Code-for-OKINAWA/covid19#570]
## 改善詳細 / Details of Improvement
- 受診・相談目安が変わったので「新型コロナウイルス感染症が心配なときに」ページの内容を更新する。
  修正が必要なページ
  「新型コロナウイルス感染症が心配なときに」
  https://okinawa.stopcovid19.jp/flow
  修正するファイル
  pages/flow.vue

## スクリーンショット / Screenshot
- 症状の目安を修正する。
![新型コロナウイルス感染症が心配なときに_沖縄県_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/39450931/81586966-52932d80-93f1-11ea-8708-07862596b756.png)

  修正内容の参考：
  厚生労働省　相談・受診の目安
  https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000121431_00094.html

**Comment by masakifujie** [comment]
ありがとうございます！
