### ISSUE TITLE
COCOAへのリンクを追加

### ISSUE THREAD

**Issue by azurata45** [Code-for-OKINAWA/covid19#691]
## 改善詳細 / Details of Improvement
- 先日、厚生労働省から新型コロナウイルス接触確認アプリ、通称「COCOA」がリリースされたため、COCOAへのリンクを追加する

**Comment by amouro** [comment]
Sidebar の中で追加します、どうですか？
![image](https://user-images.githubusercontent.com/3444618/89097443-eafde480-d419-11ea-94e5-49f0f4609399.png)

**Comment by azurata45** [comment]
良いと思います。そのままプルリクの作成をお願いします
