### ISSUE TITLE
Embed MCIPAC Okinawa COVID-19 Trace Tracker Google maps

### ISSUE THREAD

**Issue by amouro** [Code-for-OKINAWA/covid19#779]
## 改善詳細 / Details of Improvement
- Add information of the infection situation in the US military base in Okinawa
- https://www.mcipac.marines.mil/COVID-Trace-Tracking/

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/3444618/87782845-3f2b9500-c86e-11ea-9422-2998dc3f9465.png)

## 期待する見せ方・挙動 / Expected behavior
- A new block of the embedded google map

**Comment by t-ube** [comment]
当該マップは更新が2020/07に更新停止。
クローズとする。
