### ISSUE TITLE
英語版つくる

### ISSUE THREAD

**Issue by ayaneish** [Code-for-OKINAWA/covid19#82]

**Comment by amouro** [comment]
台湾から、OISTのウェブウェブデベロッパーです。
英語翻訳をやります。

I can help with the English translation.

**Comment by amouro** [comment]
質問があります
「入院調整」の意味は教えてください

**Comment by amouro** [comment]
transifexは統合されていますか？

**Comment by amouro** [comment]
レビューお願いします
