### ISSUE TITLE
「最新のお知らせ」更新について

### ISSUE THREAD

**Issue by amouro** [Code-for-OKINAWA/covid19#859]
## 改善詳細 / Details of Improvement
- Remove the older news links
- Add the recent news links

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/3444618/88999900-de519180-d330-11ea-8e21-016a2de14d11.png)

## 期待する見せ方・挙動 / Expected behavior
- I'd like to have the latest news from July
- If the news before Jun are not relevant now, we should remove them
- Please let us discuss a proper news list for the current homepage

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by sunao11** [comment]
お疲れさまです。
[私が初めて作ってみました。ミスがあれば指摘お願いします。
{
    " newsItems "：[
         {
            "日付"： " 2020 \ / 07 \ / 30 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/koho/20200730.html "、
            " text "： "沖縄県内離島への渡航について"
        }
         {
            "日付"： " 2020 \ / 07 \ / 28 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/koho/corona/20200728.html "、
            " text "： "警戒レベル第２段階の実施内容について"
        }
        {
            "日付"： " 2020 \ / 07 \ / 27 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "新型コロナウイルス感染症にかかる知事コメント"
        }
         {
            "日付"： " 2020 \ / 07 \ / 24 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_korona_event_info.html "、
            " text "： "沖縄県主催イベント等実施ガイドラインの改定について"
        }
        {
            "日付"： " 2020 \ / 07 \ / 21 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "新型コロナウイルス感染症にかかる知事コメント"
        }
        {
            "日付"： " 2020 \ / 07 \ / 20 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "新型コロナウイルス感染症にかかる知事コメント"
        }
        {
            "日付"： " 2020 \ / 07 \ / 16 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "新型コロナウイルス感染症にかかる知事コメント"
        }
         {
            "日付"： " 2020 \ / 07 \ / 11 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "新型コロナウイルス感染症にかかる知事コメント"
        }
         {
            "日付"： " 2020 \ / 07 \ / 10 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "新型コロナウイルス感染症にかかる知事コメント"
        }
         {
            "日付"： " 2020 \ / 07 \ / 08 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "新型コロナウイルス感染症にかかる知事コメント"
        }
         {
            "日付"： " 2020 \ / 07 \ / 02 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/20200727gaidorain.html "、
            " text "： "(県内事業者の皆様へ)沖縄県新型コロナウイルス感染症拡大予防ガイドラインの作成について"
        }
          {
            "日付"： " 2020 \ / 06 \ / 29 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/20200727gaidorain.html "、
            " text "： "沖縄県主催イベント等実施ガイドラインの改定について"
        }
        {
            "日付"： " 2020 \ / 06 \ / 17 "、
            " url "： "https://www.pref.okinawa.jp/site/bunka-sports/kankoshinko/ukeire/actionplan.html "、
            " text "： "沖縄 Tour Style With コロナ　旅行者の安全・安心アクションプランについて"
        }
        {
            "日付"： " 2020 \ / 06 \ / 17 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "新型コロナウイルス感染症にかかる知事コメント"
        }
        {
            "日付"： " 2020 \ / 06 \ / 17 "、
            " url "： "https://www.pref.okinawa.lg.jp/site/chijiko/koho/corona/20200617.html "、
            " text "： "沖縄県主催イベント等実施ガイドラインの改定について"
        }
         {
            "日付"： " 2020 \ / 06 \ / 03 "、
            " url "： " https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "新型コロナウイルス感染症にかかる知事コメント"
        {
            "日付"： " 2020 \ / 06 \ / 01 "、
            " url "： " https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_corona_potal.html "、
            " text "： "新型コロナウイルス感染症に関する各種情報について"
        }、
        {
            "日付"： " 2020 \ / 05 \ / 25 "、
            " url "： " https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "新型コロナウイルス感染症拡大防止にかかる知事コメント"
        }、
        {
            "日付"： " 2020 \ / 05 \ / 20 "、
            " url "： " https://www.pref.okinawa.lg.jp/site/chijiko/koho/20205020.html "、
            " text "： "沖縄県主催イベント等実施ガイドラインの策定について"
        }、
        {
            "日付"： " 2020 \ / 05 \ / 15 "、
            " url "： " https://www.pref.okinawa.lg.jp/200515.html "、
            " text "： "新型コロナウイルス感染症対策に係る県独自の実施方針策定について"
        }、
      　{
            "日付"： " 2020 \ / 05 \ / 15 "、
            " url "： " https://www.pref.okinawa.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "新型コロナウイルス感染症拡大防止にかかる知事コメント"
        }、
        {
            "日付"： " 2020 \ / 05 \ / 11 "、
            " url "： " https://www.pref.okinawa.lg.jp/site/chijiko/koho/20200511.html "、
            " text "： "沖縄県新型コロナウイルス感染症拡大予防ガイドラインの作成について"
        }、
        {
            "日付"： " 2020 \ / 05 \ / 07 "、
            " url "： " https://www.pref.okinawa.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "新型コロナウイルス感染症沖縄県緊急事態宣言を受けた沖縄県実施方針の変更について"
        }、
        {
            "日付"： " 2020 \ / 04 \ / 23 "、
            " url "： " https://www.pref.okinawa.jp/20200422.html "、
            " text "： "沖縄県緊急事態宣言を受けた沖縄県実施方針の策定について"
        }、
        {
            "日付"： " 2020 \ / 04 \ / 21 "、
            " url "： " https://www.pref.okinawa.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "新型コロナウイルス感染症沖縄県緊急事態宣言"
        }、
        {
            "日付"： " 2020 \ / 04 \ / 13 "、
            " url "： " https://www.pref.okinawa.jp/site/hoken/chiikihoken/kekkaku/2019-ncov.html "、
            " text "： "新型コロナウイルス感染症について（一般の方へ）"
        }、
        {
            "日付"： " 2020 \ / 04 \ / 10 "、
            " url "： " https://www.youtube.com/watch?v=qJVGnPjwTpo&list=PLjCs709XbPupyuNlRpPw2NrMXPmXf5cN7&index=4&t=0s "、
            " text "： "新型コロナウイルス感染症の拡大を防ぐための玉城知事から県民の皆様へのメッセージ"
        }、
        {
            "日付"： " 2020 \ / 04 \ / 10 "、
            " url "： " https://www.pref.okinawa.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html "、
            " text "： "沖縄県新型コロナウイルス感染症対策本部会議における玉城知事のコメント"
        }
    ]
}

**Comment by sunao11** [comment]
[okinawaprefecture.zip](https://github.com/Code-for-OKINAWA/covid19/files/5005749/okinawaprefecture.zip)

**Comment by sunao11** [comment]
[okinawaprefecture.zip](https://github.com/Code-for-OKINAWA/covid19/files/5009702/okinawaprefecture.zip)

**Comment by amouro** [comment]
@sunao11 資料ありがとうございます

[data/news.json](https://github.com/Code-for-OKINAWA/covid19/blob/development/data/news.json) から更新してみますか

**Comment by amouro** [comment]
@sunao11 のデータに基づいて、次のように更新します
`hompage` 条件が `true` の場合、ホームページに表示されます

`{
    "newsItems": [
        {
            "date": "2020\/08\/01",
            "url": "https://www.pref.okinawa.lg.jp/20200731.html",
            "text": "沖縄県緊急事態宣言について",
            "homepage": true
        },
        {
            "date": "2020\/07\/31",
            "url": "https://www.pref.okinawa.lg.jp/site/shoko/koyo/koyokeizoku.html",
            "text": "沖縄県雇用継続助成金（雇用調整助成金等の上乗せ助成）",
            "homepage": false
        },
        {
            "date": "2020\/07\/31",
            "url": "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html",
            "text": "新型コロナウイルス感染症にかかる知事コメント",
            "homepage": true
        },
        {
            "date": "2020\/07\/30",
            "url": "https://www.pref.okinawa.lg.jp/site/chijiko/koho/20200730.html",
            "text": "沖縄県内離島への渡航について（7月30日更新）",
            "homepage": true
        },
        {
            "date": "2020\/07\/28",
            "url": "https://www.pref.okinawa.lg.jp/site/chijiko/koho/corona/20200728.html",
            "text": "警戒レベル第２段階の実施内容について",
            "homepage": false
        },
        {
            "date": "2020\/06\/01",
            "url": "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_corona_potal.html",
            "text": "新型コロナウイルス感染症に関する各種情報について",
            "homepage": true
        },
        {
            "date": "2020\/05\/25",
            "url": "https://www.pref.okinawa.lg.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html",
            "text": "新型コロナウイルス感染症拡大防止にかかる知事コメント",
            "homepage": false
        },
        {
            "date": "2020\/05\/20",
            "url": "https://www.pref.okinawa.lg.jp/site/chijiko/koho/20205020.html",
            "text": "沖縄県主催イベント等実施ガイドラインの策定について",
            "homepage": false
        },
        {
            "date": "2020\/05\/15",
            "url": "https://www.pref.okinawa.lg.jp/200515.html",
            "text": "新型コロナウイルス感染症対策に係る県独自の実施方針策定について",
            "homepage": false
        },
        {
            "date": "2020\/05\/15",
            "url": "https://www.pref.okinawa.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html",
            "text": "新型コロナウイルス感染症拡大防止にかかる知事コメント",
            "homepage": false
        },
        {
            "date": "2020\/05\/11",
            "url": "https://www.pref.okinawa.lg.jp/site/chijiko/koho/20200511.html",
            "text": "沖縄県新型コロナウイルス感染症拡大予防ガイドラインの作成について",
            "homepage": false
        },
        {
            "date": "2020\/05\/07",
            "url": "https://www.pref.okinawa.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html",
            "text": "新型コロナウイルス感染症沖縄県緊急事態宣言を受けた沖縄県実施方針の変更について",
            "homepage": false
        },
        {
            "date": "2020\/04\/23",
            "url": "https://www.pref.okinawa.jp/20200422.html",
            "text": "沖縄県緊急事態宣言を受けた沖縄県実施方針の策定について",
            "homepage": false
        },
        {
            "date": "2020\/04\/21",
            "url": "https://www.pref.okinawa.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html",
            "text": "新型コロナウイルス感染症　沖縄県緊急事態宣言",
            "homepage": false
        },
        {
            "date": "2020\/04\/13",
            "url": "https://www.pref.okinawa.jp/site/hoken/chiikihoken/kekkaku/2019-ncov.html",
            "text": "新型コロナウイルス感染症について（一般の方へ）",
            "homepage": false
        },
        {
            "date": "2020\/04\/10",
            "url": "https://www.youtube.com/watch?v=qJVGnPjwTpo&list=PLjCs709XbPupyuNlRpPw2NrMXPmXf5cN7&index=4&t=0s",
            "text": "新型コロナウイルス感染症の拡大を防ぐための玉城知事から県民の皆様へのメッセージ",
            "homepage": false
        },
        {
            "date": "2020\/04\/10",
            "url": "https://www.pref.okinawa.jp/site/chijiko/kohokoryu/koho/2020_new_korona_virs.html",
            "text": "沖縄県新型コロナウイルス感染症対策本部会議における玉城知事のコメント",
            "homepage": false
        }
    ]
}
`

**Comment by amouro** [comment]
![image](https://user-images.githubusercontent.com/3444618/89097130-264ae400-d417-11ea-8553-12c23b782424.png)

**Comment by sunao11** [comment]
ありがとうございます。
