### ISSUE TITLE
【最新のお知らせ】に出す情報を考える

### ISSUE THREAD

**Issue by wanwanland** [Code-for-OKINAWA/covid19#88]

**Comment by ayaneish** [comment]
市中感染者・感染経路不明者の数

**Comment by mami-miyagi** [comment]
沖縄県公式HP発信の情報を随時載せていく。

沖縄県公式HP
■健康・医療・福祉
https://www.pref.okinawa.jp/site/kenko/index.html
■暮らし・環境
https://www.pref.okinawa.jp/site/kurashi/index.html
■産業・仕事
https://www.pref.okinawa.jp/site/sangyo/index.html

コロナに関する情報が載っていそうな分野をピックアップ。
午前中と夕方に県公式HPを確認し、コロナ関連の記事が掲載されたら、コロナ対策サイトの「最新のお知らせ」に載せる。

**Comment by skurima** [comment]
県内2紙とも公式サイトに新型コロナ関連のまとめページを作っていますね。
こちらをスクレイピングさせてもらってメディアの情報として出すのはどうでしょう。
＃両サイトがRSS出してくれるといいんだけど

ほんとは公式情報が望ましいんだけど、ニュースがでてから実際に更新されるまでタイムラグがあるし、県庁のサイト自体もアクセスが多いせいか重くなってますね。

新型肺炎 -琉球新報 - 沖縄の新聞、地域のニュース https://ryukyushimpo.jp/tag/%E6%96%B0%E5%9E%8B%E8%82%BA%E7%82%8E/
新型コロナウイルスの記事一覧 | 沖縄タイムス＋プラス https://www.okinawatimes.co.jp/subcategory/%E6%96%B0%E5%9E%8B%E3%82%B3%E3%83%AD%E3%83%8A%E3%82%A6%E3%82%A4%E3%83%AB%E3%82%B9

「見出し」「更新日時」「媒体名」というフォーマットで、

沖縄、新たに5人コロナ感染　１日あたり最多、県関連17人に - 琉球新報 - 沖縄の新聞、地域のニュース https://ryukyushimpo.jp/news/entry-1101817.html

の場合だと、

[沖縄、新たに5人コロナ感染　１日あたり最多、県関連17人に](https://ryukyushimpo.jp/news/entry-1101817.html) - 2020年4月4日 10:29 - 琉球新報

みたいなのを、時系列降順に並べたやつ。
