### ISSUE TITLE
外からプルリクを出せる仕組みを作る

### ISSUE THREAD

**Issue by wanwanland** [Code-for-OKINAWA/covid19#89]

**Comment by masakifujie** [comment]
まぁしさん

**Comment by chinen-octtn** [comment]
Collaboraterに追加しなくても、プルリクエストが作成できる権限設定になっていることを確認しました。

## コード更新の手順について
1. 作業するissueに「やります！」等とコメントしてから、リポジトリをForkして開発を始める
2. Forkしたリポジトリで、作業ブランチを作成して開発する
3. 作業完了したら、フォーク元のdevelopブランチへプルリクエストを作成
4. サイト管理者がレビュー後、修正依頼・もしくはマージのやり取りで完了

この手順で、Collaboraterでなくてもプルリクエストできます。
（[貢献の仕方](https://github.com/Code-for-OKINAWA/covid19/blob/development/CONTRIBUTING.md)ページへ追加するよう mamiさんに相談済み）

develop、masterへマージできるのはCollaboraterのみとします。

**Comment by chinen-octtn** [comment]
外部からプルリクエストできることが検証できたので、closeします！
