### ISSUE TITLE
githubのレポジトリ管理人を決める

### ISSUE THREAD

**Issue by wanwanland** [Code-for-OKINAWA/covid19#90]

**Comment by masakifujie** [comment]
まぁしさん担当

**Comment by chinen-octtn** [comment]
# リポジトリの管理者について（案）

developブランチ（ステージング環境）、master(本番環境）へマージできるのはGitHubのCollaboraterのみとする。

権限設定では、Gitリポジトリに招待しなくても、Forkしてプルリクエストの作成が可能。

マージ前にチェック（レビュー）を挟むことで、ミスや脆弱性といったリスクを最小限にする体制とする。

Collaboraterは、知り合いづて、または所属がわかる人であれば追加しても良いとする。
Code for Okinawa #コロナ対策 チャンネルのメンバーから招待してOK。

現状マージ、レビューできる人員が少ないため、僕の知人からも数人、協力者を追加する。

**Comment by chinen-octtn** [comment]
Wikiにまとめたのでcloseします！
https://github.com/Code-for-OKINAWA/covid19/wiki/%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE%E7%AE%A1%E7%90%86%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
