### ISSUE TITLE
CONTRIBUTING.md を沖縄版に変更

### ISSUE THREAD

**Issue by wanwanland** [Code-for-OKINAWA/covid19#91]

**Comment by chinen-octtn** [comment]
このページを沖縄版の内容に改修したら、良さそうです！
https://github.com/Code-for-OKINAWA/covid19/blob/development/CONTRIBUTING.md

**Comment by chinen-octtn** [comment]
ラベルについては、沖縄版のラベルを整理したほうが良さそう。

* 優先度：高
* 優先度：中 
* 優先度：低
* 他にどれを使うか

> waiting ラベルがついた Issue は関係者の確認中ですので、内容が固まるまで実装するのは避けていただく方が無難です。
> good first issue / help wanted / bug を優先して対応いただけると助かります

**Comment by mami-miyagi** [comment]
ラベルと注釈の変更内容
ーーーーーーーーーーーーーーーーーーーー
- 優先度：高

- 優先度：中

- 優先度：低

- 確認待ち

「確認待ち」ラベルがついたIssueは関係者の確認中ですので、内容が固まるまで実装するのは避けていただく方が無難です。
優先度：高 / 優先度：中 / 優先度：低　を優先して対応頂けると助かります。

ーーーーーーーーーーーーーーーーーーーー
はどうだろう。

**Comment by mami-miyagi** [comment]
削除を考えている項目
ーーーーーーーーーーーーーーーーーーーー
- 参加にあたって＞コミュニケーションにあたっては、Code for Japan の 行動規範 もご確認ください。（Code for Japanバージョンがないため）
- 参考情報＞東京都 新型コロナウイルス対策サイトへの貢献方法を解説(Qiita)
- CONTRIBUTORS.md への追加について
- 開発に関する情報＞ステージングサイト（完成次第追加）
- 開発に関する情報＞デザイン
- 開発に関する情報＞翻訳スプレッドシート
ーーーーーーーーーーーーーーーーーーーー
どうでしょう。

**Comment by chinen-octtn** [comment]
@mami-miyagi 
ラベルについて、方向性は良さそうです！

ちょっとだけ書き方かえて、

> 優先度：高 / 優先度：中 / 優先度：低　を優先して対応頂けると助かります。

↓

優先度：高 / 優先度：中 / 優先度：低　の順に対応頂けると助かります。

こちらでどうでしょうか？

**Comment by chinen-octtn** [comment]
@mami-miyagi 
削除を考えている項目、良いと思います！

「参加にあたって」の部分、
作業手順のような項目をこんな感じで入れてまとめたいです。

```
## コード更新の手順について
1. 作業するissueに「やります！」等とコメントしてから、リポジトリをForkして開発を始める
2. Forkしたリポジトリで、作業ブランチを作成して開発する
3. 作業完了したら、フォーク元のdevelopブランチへプルリクエストを作成
4. サイト管理者がレビュー後、修正依頼・もしくはマージのやり取りで完了

ForkなどGitHub自体の操作は、東京都版の手順をわかりやすく解説している記事があるので参考にしてください。
※間違えて東京版にプルリクエストしないよう注意！
https://qiita.com/FPC_COMMUNITY/items/b9cc072813dc2231b2b2
```
