### ISSUE TITLE
検査件数を追加

### ISSUE THREAD

**Issue by ayaneish** [Code-for-OKINAWA/covid19#92]

**Comment by masakifujie** [comment]
#
<img width="543" alt="スクリーンショット 2020-04-08 19 10 20" src="https://user-images.githubusercontent.com/62975418/78772437-bc707f80-79cc-11ea-88e7-9b2d162fa44f.png">

**Comment by masakifujie** [comment]
東京の表をそのまま貼って数字を更新していくのはどうでしょう？

**Comment by mami-miyagi** [comment]
<img width="565" alt="スクリーンショット 2020-04-08 22 53 43" src="https://user-images.githubusercontent.com/38314424/78792266-dff6f280-79eb-11ea-92af-f84e238c3d7a.png">
検査(実施)件数であれば、この表が対応しているかも。

**Comment by masakifujie** [comment]
そうですね！こちらが正確です！

**Comment by masakifujie** [comment]
@amouro さん
Could you make 検査実地件数 graph that connect to sammary csv as well?

**Comment by masakifujie** [comment]
![都内の最新感染動向___東京都_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/62975418/80062214-2ca30780-856e-11ea-8071-e96bf434aa14.jpg)

![無題のスプレッドシート_-_Google_スプレッドシート](https://user-images.githubusercontent.com/62975418/80062342-7390fd00-856e-11ea-9e06-ff03edca9d86.jpg)

**Comment by masakifujie** [comment]
水谷さんが今までのCSVを作成してくれている。
https://codeforokinawa.slack.com/archives/C01119TC1HQ/p1587707048493400?thread_ts=1587702958.491100&cid=C01119TC1HQ

**Comment by amouro** [comment]
I'm working on this issue but I found the data is not reliable

1. 検査人数累計 and 検査実施人数 are not related
![image](https://user-images.githubusercontent.com/3444618/82462094-1bf69a80-9af6-11ea-8ce0-aae6b864afc1.png)

1. Lots of days are missing (There are 13 Days without data)
![image](https://user-images.githubusercontent.com/3444618/82462275-56603780-9af6-11ea-9069-ba3145fbce9e.png)

@masakifujie さん would you ask Takesue san about it? The data source is problematic and not usable for this diagram.

**Comment by amouro** [comment]
I made the card and also update the automate converter.
But because of the problem of the data, this chart is not correct and is not reliable.

![image](https://user-images.githubusercontent.com/3444618/82463263-907e0900-9af7-11ea-9291-71bc8cbe3971.png)

![image](https://user-images.githubusercontent.com/3444618/82463310-a390d900-9af7-11ea-8bde-418a2d896898.png)

**Comment by amouro** [comment]
if we can have all daily 検査実施人数 data, it's good to merge.

**Comment by amouro** [comment]
This doesn't deploy to live site correctly?

**Comment by masakifujie** [comment]
Yes, It's not correct .
Is it possible to fix for update live site?

**Comment by amouro** [comment]
@masakifujie Since you've updated the summary.csv and the converter ran automatically. It is correct and match to the data now.
