### ISSUE TITLE
陽性患者数(日別/累計)で陽性患者確認数が0の日の場合にグラフが表示されていない。

### ISSUE THREAD

**Issue by yhirochick** [Code-for-OKINAWA/covid19#94]
## 改善詳細 / Details of Improvement
- 陽性患者数(日別/累計)グラフの3/28よりも前の日付で、陽性患者が確認されなかった日がグラフに表示されていない。そのため日別、累計それぞれのグラフで一見、毎日患者が発生しているような印象を受ける。
- data/data.jsonで3/30以降と同様に確認患者数が0のときもデータを追加する必要がある。

## スクリーンショット / Screenshot
現状のグラフ
- 日別
![image](https://user-images.githubusercontent.com/12014751/78364286-2a492f80-75f8-11ea-9d4b-49ed23ceffb4.png)

- 累計
![image](https://user-images.githubusercontent.com/12014751/78364311-359c5b00-75f8-11ea-9414-c27a44c277ba.png)

## 期待する見せ方・挙動 / Expected behavior
- 日別
![image](https://user-images.githubusercontent.com/12014751/78364461-709e8e80-75f8-11ea-8844-71e602710267.png)
- 累計
![image](https://user-images.githubusercontent.com/12014751/78364505-8613b880-75f8-11ea-8f22-116b7add801a.png)

**Comment by yhirochick** [comment]
あと、すみません。
縦軸の刻みが0.5人になっているのも気になります。1人でよいかと。

**Comment by amouro** [comment]
2/22 から 3/23 まで感染者がいません、どうしましょうか？
![Screen Shot on 2020-04-04 at 23:57:11](https://user-images.githubusercontent.com/3444618/78454010-4e783f80-76d0-11ea-8c44-37df261637ce.png)

もし全部追加する、その感じです
- 日別
![image](https://user-images.githubusercontent.com/3444618/78454129-145b6d80-76d1-11ea-92aa-d2a538602e0a.png)
![image](https://user-images.githubusercontent.com/3444618/78454140-2a692e00-76d1-11ea-906a-e6457b8f1857.png)
- 累計
![image](https://user-images.githubusercontent.com/3444618/78454143-3359ff80-76d1-11ea-9403-6994790b1d79.png)

**Comment by yhirochick** [comment]
@amouro 
あ、たしかにそうですね。
すみません。issue上げるときに僕も見間違えていました。

2/22~3/23の患者数0を追加するとたしかにグラフが急に変わるので違和感感じますが、
このほうがより正確に実態を表していると思います。

ただ、もともとの0が表示されていないグラフにもなにか意図があるかもしれないので
最終的な判断はサイト管理者に任せたほうがいいかなと思います。
