### ISSUE TITLE
data.jsonの中にある日付で2018年になっているものがある

### ISSUE THREAD

**Issue by tamitami5c** [Code-for-OKINAWA/covid19#949]
## 起こっている問題 / The Problem

data.jsonの中にある日付で2018年になっているものがある。

https://github.com/Code-for-OKINAWA/covid19/blob/85a2f39a248a7b1a6d1b757280e215327e572972/data/data.json#L6

や

>            {
>                 "日付": "2020-08-18T08:00:00.000Z",
>                 "小計": 0
>             },
>             {
>                 "日付": "2018-08-18T08:00:00.000Z",
>                 "小計": 33
>             }

など

## 期待する見せ方・挙動 / Expected Behavior

2018 -> 2020

**Comment by amouro** [comment]
Thanks for the report. This is fixed from the last deployment.
